# Generated by Django 4.2.1 on 2023-05-16 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myBackupApp', '0005_company_remark'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='opend',
            field=models.BooleanField(default=False),
        ),
    ]
