# Generated by Django 4.2.1 on 2023-05-16 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myBackupApp', '0006_company_opend'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='logo_height',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='logo_width',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='logo',
            field=models.ImageField(blank=True, height_field='logo_height', null=True, upload_to='company', width_field='logo_width'),
        ),
    ]
