# Generated by Django 4.2.1 on 2023-05-21 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myBackupApp', '0007_company_logo_height_company_logo_width_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='logo_height',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='logo_width',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
