# Generated by Django 4.2.1 on 2023-05-21 17:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myBackupApp', '0008_alter_company_logo_height_alter_company_logo_width'),
    ]

    operations = [
        migrations.CreateModel(
            name='RealUserEntity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('realname', models.CharField(max_length=20, verbose_name='真實姓名')),
                ('number', models.CharField(max_length=10, verbose_name='證件號碼')),
                ('real_type', models.IntegerField(choices=[(0, '身分證'), (1, '駕照'), (2, '護照')], verbose_name='證件類型')),
                ('image1', models.ImageField(upload_to='user/real', verbose_name='正面照')),
                ('image2', models.ImageField(upload_to='user/real', verbose_name='反面照')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='myBackupApp.userentity')),
            ],
            options={
                'verbose_name': '實名認證表',
                'verbose_name_plural': '實名認證表',
                'db_table': 't_realuser',
            },
        ),
    ]
